name: Publish

on:
  push:
    branches: [ main ]

jobs:
  publish:
    name: Publish NPM Package
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
